newpcsoftapp/grails-app/domain/newpcsoftapp/Consumer.groovy
package newpcsoftapp


class Consumer {
	String username
	String password
	String password2
	
	static transients = ['password2']
	
	static hasMany = [complaint: Complaint]
	
	String toString() { return username}

    static constraints = {
	username(unique:true)
	password (size:6..10, blank:false, matches:/[\S]+/, validator:{val, obj ->
			if (obj.password != obj.password2)
			return 'user.password.dontmatch'})
	password2 bindable: true
    }
	
	
}

newpcsoftapp/grails-app/domain/newpcsoftapp/Response.groovy
package newpcsoftapp

class Response {

	Complaint complaint
	Date dateCreated
	String body
	
    static constraints = {
	dateCreated()
	body()
	complaint()
    }
	
	String toString(){
	"${this.complaint.subject} reply"
	}
	
	
}

newpcsoftapp/grails-app/controllers/newpcsoftapp/ConsumerController.groovy
package newpcsoftapp

import org.springframework.dao.DataIntegrityViolationException

class ConsumerController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        [consumerInstanceList: Consumer.list(params), consumerInstanceTotal: Consumer.count()]
    }

    def create() {
        [consumerInstance: new Consumer(params)]
    }

    def save() {
        def consumerInstance = new Consumer(params)
        if (!consumerInstance.save(flush: true)) {
            render(view: "create", model: [consumerInstance: consumerInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'consumer.label', default: 'Consumer'), consumerInstance.id])
        redirect(action: "afterSave", id: consumerInstance.id)
    }
	
	def afterSave(Long id) {
        def consumerInstance = Consumer.get(id)
        if (!consumerInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'consumer.label', default: 'Consumer'), id])
            redirect(action: "list")
            return
        }

        [consumerInstance: consumerInstance]
    }
	
		def logoutPage(Long id) {
        def consumerInstance = Consumer.get(id)
        if (!consumerInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'consumer.label', default: 'Consumer'), id])
            redirect(action: "list")
            return
        }

        [consumerInstance: consumerInstance]
    }
	
	

    def show(Long id) {
        def consumerInstance = Consumer.get(id)
        if (!consumerInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'consumer.label', default: 'Consumer'), id])
            redirect(action: "list")
            return
        }

        [consumerInstance: consumerInstance]
    }
	
	
	
    def edit(Long id) {
        def consumerInstance = Consumer.get(id)
        if (!consumerInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'consumer.label', default: 'Consumer'), id])
            redirect(action: "list")
            return
        }

        [consumerInstance: consumerInstance]
    }

    def update(Long id, Long version) {
        def consumerInstance = Consumer.get(id)
        if (!consumerInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'consumer.label', default: 'Consumer'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (consumerInstance.version > version) {
                consumerInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'consumer.label', default: 'Consumer')] as Object[],
                          "Another user has updated this Consumer while you were editing")
                render(view: "edit", model: [consumerInstance: consumerInstance])
                return
            }
        }

        consumerInstance.properties = params

        if (!consumerInstance.save(flush: true)) {
            render(view: "edit", model: [consumerInstance: consumerInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'consumer.label', default: 'Consumer'), consumerInstance.id])
        redirect(action: "show", id: consumerInstance.id)
    }

    def delete(Long id) {
        def consumerInstance = Consumer.get(id)
        if (!consumerInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'consumer.label', default: 'Consumer'), id])
            redirect(action: "list")
            return
        }

        try {
            consumerInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'consumer.label', default: 'Consumer'), id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'consumer.label', default: 'Consumer'), id])
            redirect(action: "show", id: id)
        }
    }

	
	def login = {
		if (request.method == "GET") {
			session.username = null
			def consumer = new Consumer()
		}
		else {
		
		def consumer = Consumer.findByUsernameAndPassword(params.username,params.password)
		if (consumer) {
			session.username = consumer.username
			//redirect(controller:'room')
			def redirectParams =session.originalRequestParams?session.originalRequestParams:[controller:'consumer']
			redirect(controller: 'consumer', action:'logoutPage')
		}

		else {
		flash['message'] = 'Please enter a valid username and password'
		}

	}
	}
	
	
	def logout = {
		session.accountId = null
		session.username = null
		flash.message = 'Successfully logged out'
		render(view: 'afterSave')
	}
}

newpcsoftapp/grails-app/views/consumer/_form.gsp
<%@ page import="newpcsoftapp.Consumer" %>

<div class="dialog" align="center">
						<table>
							<tr class='prop'>
								<td valign='top' class='name'>
								<center>	<label for='username'>Username:</label></center>
								</td>
								<td valign='top' class='value '>
									<input type="text" maxlength='8'
										name='username'
										value='${consumer?.username}'
										class="required input_field"
										>
									</input>
								</td>
							</tr>
							<tr class='prop'>
								<td valign='top' class='name'>
								<center>	<label for='password'>Password:</label></center>
								</td></br>
								<td valign='top' class='value '>
									<input type="password" maxlength='8'
									name='password'
									value='${consumer?.password}'
									class="required input_field"
									>
									</input>
								
								</td>
							</tr>
							<tr class='prop'>
								<td valign='top' class='name'>
								<center>	<label for='password'>Confirm Password:</label></center>
								</td></br>
								<td valign='top' class='value '>
									<input type="password" maxlength='8'
									name='password2'
									value='${consumer?.password2}'
									class="required input_field"
									>
									</input>
								
								</td>
							</tr>
						</table>
</div>
					

<!--	
<div class="fieldcontain ${hasErrors(bean: consumerInstance, field: 'complaint', 'error')} ">
	<label for="complaint">
		<g:message code="consumer.complaint.label" default="Complaint" />
		
	</label>


<ul class="one-to-many">
<g:each in="${consumerInstance?.complaint?}" var="c">
    <li><g:link controller="complaint" action="show" id="${c.id}">${c?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="complaint" action="create" params="['consumer.id': consumerInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'complaint.label', default: 'Complaint')])}</g:link>
</li>
</ul>
-->

newpcsoftapp/grails-app/views/consumer/afterSave.gsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta name="layout" content="mainafterLogin"/>
<title>PCMA</title>

</head>
<body>

<div id="templamteo_body_wrapper">
<div id="templatemo_wrapper">
	<div id="templatemo_main_top"></div>
    <div id="templatemo_main">
    
    	<div id="templatemo_sidebar">
        	
            <div id="site_title"><h1><a href="/newpcsoftapp" rel="nofollow">Website Name</a><span><a href="#" target="_blank">Power Consumption Monitoring Software Application (PCMSA)</a></span></h1></div>
            
            <div id="templatemo_menu">
                <ul>
                    <li><a href="${createLink(uri: '/')}" class="current">Home</a></li>
					<li><a href="/newpcsoftapp/consumer/login">Login</a></li>
					<li><a href="#">Monitoring Portal</a></li>
                    <li><a href="#">Devices</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
           
                				
			</div>
            
            <div class="sb_box">
	            <h3>Search</h3>
            	<div id="search">
                    <form action="#" method="get">
                        <input type="text" value="Search" name="q" size="10" id="searchfield" title="searchfield" onfocus="clearText(this)" onblur="clearText(this)" />
                        <input type="submit" name="Search" value="Search" id="searchbutton" title="Search" />
                    </form>
				</div>
            </div>
            
			
            
            <div class="cleaner"></div>
        </div> <!-- end of sidebar -->
        
        <div id="templatemo_content">
        	
<!--            <div id="slider">
            	<img src="images/slideshow/ILPIHotlines.jpg" alt="Image 5" title="We are just one call away! We are so dear to serve you. :)" />
				<img src="images/slideshow/PayOnline.jpg" alt="Image 1" title="Pay your bills online. It is fast and easy!" />
                <img src="images/slideshow/ElectricSafety Tips.jpg" alt="Image 2" title="Tip: Avoid flying kites near electric transmission and distribution lines." />
                <img src="images/slideshow/RA7832.jpg" alt="Image 3" title="Do not steal electricity. Be a responsible citizen!" />
                <img src="images/slideshow/OfficeHours.jpg" alt="Image 4" title="Inquire to us now. We are so excited to serve you. :)" />
        	</div>
-->
            <div class="content_box">
            	<h2>Welcome to Mirax Development</h2>
                <p>"The best part is that I know my exact energy footprint pattern and can control it. I know what is waste vs. necessity. I have completely eliminated expensive and unnecessary consumption." </br><em>-Chris Hunt, San Carlos CA</em></p>
				Login <a href="/newpcsoftapp/consumer/login">here</a> to continue.
            </div>
            
            
        </div> <!-- end of content -->
		
		
    	<div class="cleaner"></div>
    </div> <!-- end of main -->
    <div id="templatemo_footer">
    
        Copyright &#169; 2014 <a href="/">Mirax Development - Power Consumption Monitoring Software Application</a>
        
    </div> <!-- end of templatemo_footer -->
</div> <!-- end of wrapper -->
</div>
<g:javascript src = "logging.js" />

</body>
</html>

newpcsoftapp/grails-app/views/consumer/create.gsp
<%@ page import="newpcsoftapp.Consumer" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta name="layout" content="main"/>
<title>PCMA</title>

</head>
<body>

<div id="templamteo_body_wrapper">
<div id="templatemo_wrapper">
	<div id="templatemo_main_top"></div>
    <div id="templatemo_main">
    
    	<div id="templatemo_sidebar">
        	
            <div id="site_title"><h1><a href="http://www.templatemo.com" rel="nofollow">Website Name</a><span><a href="http://fr.mystockphoto.com" title="Stockphotos"  target="_blank">Power Consumption Monitoring Software Application (PCMSA)</a></span></h1></div>
            
            <div id="templatemo_menu">
                <ul>
                    <li><a href="${createLink(uri: '/')}">Home</a></li>
					<li><a href="/newpcsoftapp/consumer/login" class="current">Login</a></li>
                    <li><a href="#">Monitoring Portal</a></li>
                    <li><a href="#">Devices</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>    	
			</div>
            
            <div class="sb_box">
	            <h3>Search</h3>
            	<div id="search">
                    <form action="#" method="get">
                        <input type="text" value="Search" name="q" size="10" id="searchfield" title="searchfield" onfocus="clearText(this)" onblur="clearText(this)" />
                        <input type="submit" name="Search" value="Search" id="searchbutton" title="Search" />
                    </form>
				</div>
            </div>
            
			
            
            <div class="cleaner"></div>
        </div> <!-- end of sidebar -->
        
        <div id="templatemo_content">
            
            <div class="content_box">
            	<h2>Sign Up</h2>
				<div id="cp_contact_form">
                <g:if test="${flash.message}">
					<div class="message">${flash.message}</div>
				</g:if>
				<g:hasErrors bean="${race}">
					<div class="errors">
					<g:renderErrors bean="${consumer}" as="list" />
					</div>
				</g:hasErrors>
				<g:form action="save" >
				<div class="dialog" align="center">
					<g:render template="form"/>
				</div>
					<g:submitButton name="create" class="save" class="submit_btn float_r" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</g:form>
				</div>
            
         
			</div> <!-- end of content -->
		
		
    	<div class="cleaner"></div>
    </div> <!-- end of main -->
    <div id="templatemo_footer">
    
        Copyright &#169; 2014 <a href="/">Mirax Development - Power Consumption Monitoring Software Application</a>
        
    </div> <!-- end of templatemo_footer -->
</div> <!-- end of wrapper -->
</div>
<g:javascript src = "logging.js" />

</body>
</html>

newpcsoftapp/grails-app/views/consumer/edit.gsp
<%@ page import="newpcsoftapp.Consumer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'consumer.label', default: 'Consumer')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-consumer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-consumer" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${consumerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${consumerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${consumerInstance?.id}" />
				<g:hiddenField name="version" value="${consumerInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

newpcsoftapp/grails-app/views/consumer/inbox.gsp
<%@ page import="newpcsoftapp.Response" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'response.label', default: 'Response')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-response" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-response" class="content scaffold-list" role="main">
			<h1>Inbox</h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<th>Subject</th>
					
						<g:sortableColumn property="body" title="${message(code: 'response.body.label', default: 'Body')}" />
					
						<th><g:message code="response.complaint.label" default="Complaint" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${responseInstanceList}" status="i" var="responseInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${responseInstance.id}" controller="response">${responseInstance.complaint.subject} response</g:link></td>
					
						<td>${fieldValue(bean: responseInstance, field: "body")}</td>
					
						<td>${fieldValue(bean: responseInstance, field: "complaint")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			
		</div>
	</body>
</html>

newpcsoftapp/grails-app/views/consumer/list.gsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta name="layout" content="main"/>
<title>PCMA</title>

</head>
<body>

<div id="templamteo_body_wrapper">
<div id="templatemo_wrapper">
	<div id="templatemo_main_top"></div>
    <div id="templatemo_main">
    
    	<div id="templatemo_sidebar">
        	
            <div id="site_title"><h1><a href="/newpcsoftapp" rel="nofollow">Website Name</a><span><a href="#" target="_blank">Power Consumption Monitoring Software Application (PCMSA)</a></span></h1></div>
            
            <div id="templatemo_menu">
                <ul>
                    <li><a href="${createLink(uri: '/')}" class="current">Home</a></li>
					<g:if test="${!session.username}">
						<li><a class="logout" href="/newpcsoftapp/consumer/login">Login</a></li>
					</g:if>
					<g:else>
						<li><a class="logout" href="/newpcsoftapp/consumer/logout">Logout</a></li>
					</g:else>
					<li><a href="/newpcsoftapp/complaint/create">Create</a></li>
					<li><a href="#">Monitoring Portal</a></li>
                    <li><a href="#">Devices</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
           
                				
			</div>
            
            <div class="sb_box">
	            <h3>Search</h3>
            	<div id="search">
                    <form action="#" method="get">
                        <input type="text" value="Search" name="q" size="10" id="searchfield" title="searchfield" onfocus="clearText(this)" onblur="clearText(this)" />
                        <input type="submit" name="Search" value="Search" id="searchbutton" title="Search" />
                    </form>
				</div>
            </div>
            
			
            
            <div class="cleaner"></div>
        </div> <!-- end of sidebar -->
        
        <div id="templatemo_content">
        	
            <div id="slider">
            	<img src="images/slideshow/ILPIHotlines.jpg" alt="Image 5" title="We are just one call away! We are so dear to serve you. :)" />
				<img src="images/slideshow/PayOnline.jpg" alt="Image 1" title="Pay your bills online. It is fast and easy!" />
                <img src="images/slideshow/ElectricSafety Tips.jpg" alt="Image 2" title="Tip: Avoid flying kites near electric transmission and distribution lines." />
                <img src="images/slideshow/RA7832.jpg" alt="Image 3" title="Do not steal electricity. Be a responsible citizen!" />
                <img src="images/slideshow/OfficeHours.jpg" alt="Image 4" title="Inquire to us now. We are so excited to serve you. :)" />
        	</div>
            
            <div class="content_box">
            	<h2>Welcome to Mirax Development</h2>
                <p>"The best part is that I know my exact energy footprint pattern and can control it. I know what is waste vs. necessity. I have completely eliminated expensive and unnecessary consumption." </br><em>-Chris Hunt, San Carlos CA</em></p>
             
            </div>
            
            
        </div> <!-- end of content -->
		
		
    	<div class="cleaner"></div>
    </div> <!-- end of main -->
    <div id="templatemo_footer">
    
        Copyright &#169; 2014 <a href="/">Mirax Development - Power Consumption Monitoring Software Application</a>
        
    </div> <!-- end of templatemo_footer -->
</div> <!-- end of wrapper -->
</div>
<g:javascript src = "logging.js" />

</body>
</html>

newpcsoftapp/grails-app/views/consumer/login.gsp
<%@ page import="newpcsoftapp.Consumer" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta name="layout" content="main"/>
<title>PCMA</title>

</head>
<body>

<div id="templamteo_body_wrapper">
<div id="templatemo_wrapper">
	<div id="templatemo_main_top"></div>
    <div id="templatemo_main">
    
    	<div id="templatemo_sidebar">
        	
            <div id="site_title"><h1><a href="http://www.templatemo.com" rel="nofollow">Website Name</a><span><a href="http://fr.mystockphoto.com" title="Stockphotos"  target="_blank">Power Consumption Monitoring Software Application (PCMSA)</a></span></h1></div>
            
            <div id="templatemo_menu">
                <ul>
                    <li><a href="${createLink(uri: '/')}">Home</a></li>
					<li><a href="/newpcsoftapp/consumer/login" class="current">Login</a></li>
                    <li><a href="#">Monitoring Portal</a></li>
                    <li><a href="#">Devices</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>    	
			</div>
            
            <div class="sb_box">
	            <h3>Search</h3>
            	<div id="search">
                    <form action="#" method="get">
                        <input type="text" value="Search" name="q" size="10" id="searchfield" title="searchfield" onfocus="clearText(this)" onblur="clearText(this)" />
                        <input type="submit" name="Search" value="Search" id="searchbutton" title="Search" />
                    </form>
				</div>
            </div>
            
			
            
            <div class="cleaner"></div>
        </div> <!-- end of sidebar -->
        
        <div id="templatemo_content">
            
            <div class="content_box">
            	<h2>Login</h2>
				<div id="cp_contact_form">
                <g:if test="${flash.message}">
					<div class="message">${flash.message}</div>
				</g:if>
				<g:hasErrors bean="${race}">
					<div class="errors">
					<g:renderErrors bean="${consumer}" as="list" />
					</div>
				</g:hasErrors>
				<g:form controller="consumer" method="post" >
					<div class="dialog" align="center">
						<table>
							<tr class='prop'>
								<td valign='top' class='name'>
								<center>	<label for='username'>Username:</label></center>
								</td>
								<td valign='top' class='value '>
									<input type="text" maxlength='8'
										name='username'
										value='${consumer?.username}'
										class="required input_field"
										>
									</input>
								</td>
							</tr>
							<tr class='prop'>
								<td valign='top' class='name'>
								<center>	<label for='password'>Password:</label></center>
								</td></br>
								<td valign='top' class='value '>
									<input type="password" maxlength='8'
									name='password'
									value='${consumer?.password}'
									class="required input_field"
									>
									</input>
								
								</td>
							</tr>
						</table>
					</div>
					<div class="buttons" align="center">
						<span class="button">
							<g:actionSubmit class="submit_btn float_r" id="submit" value="Log in" />
							
						</span>
					</div>
			</g:form>
             </div>
            </div>
            
         No account? Sign up <a href="/newpcsoftapp/consumer/create">here</a>!
		 <br>
		 For Distributor's account, sign in <a href="/newpcsoftapp/distributor/login">here</a>.
        </div> <!-- end of content -->
		
		
    	<div class="cleaner"></div>
    </div> <!-- end of main -->
    <div id="templatemo_footer">
    
        Copyright &#169; 2014 <a href="/">Mirax Development - Power Consumption Monitoring Software Application</a>
        
    </div> <!-- end of templatemo_footer -->
</div> <!-- end of wrapper -->
</div>
<g:javascript src = "logging.js" />

</body>
</html>

newpcsoftapp/grails-app/views/consumer/logoutPage.gsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta name="layout" content="main"/>
<title>PCMA</title>

</head>
<body>

<div id="templamteo_body_wrapper">
<div id="templatemo_wrapper">
	<div id="templatemo_main_top"></div>
    <div id="templatemo_main">
    
    	<div id="templatemo_sidebar">
        	
            <div id="site_title"><h1><a href="/newpcsoftapp" rel="nofollow">Website Name</a><span><a href="#" target="_blank">Power Consumption Monitoring Software Application (PCMSA)</a></span></h1></div>
            
            <div id="templatemo_menu">
                <ul>
                    <li><a href="${createLink(uri: '/')}" class="current">Home</a></li>
					<li><a href="/newpcsoftapp/consumer/logout">Logout</a></li>
					<li><a href="#">Monitoring Portal</a></li>
                    <li><a href="#">Devices</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
           
                				
			</div>
            
            <div class="sb_box">
	            <h3>Search</h3>
            	<div id="search">
                    <form action="#" method="get">
                        <input type="text" value="Search" name="q" size="10" id="searchfield" title="searchfield" onfocus="clearText(this)" onblur="clearText(this)" />
                        <input type="submit" name="Search" value="Search" id="searchbutton" title="Search" />
                    </form>
				</div>
            </div>
            
			
            
            <div class="cleaner"></div>
        </div> <!-- end of sidebar -->
        
        <div id="templatemo_content">
        	
            <div id="slider">
            	<img src="images/slideshow/ILPIHotlines.jpg" alt="Image 5" title="We are just one call away! We are so dear to serve you. :)" />
				<img src="images/slideshow/PayOnline.jpg" alt="Image 1" title="Pay your bills online. It is fast and easy!" />
                <img src="images/slideshow/ElectricSafety Tips.jpg" alt="Image 2" title="Tip: Avoid flying kites near electric transmission and distribution lines." />
                <img src="images/slideshow/RA7832.jpg" alt="Image 3" title="Do not steal electricity. Be a responsible citizen!" />
                <img src="images/slideshow/OfficeHours.jpg" alt="Image 4" title="Inquire to us now. We are so excited to serve you. :)" />
        	</div>
            
            <div class="content_box">
            	<h2>Welcome to Mirax Development</h2>
                <p>"The best part is that I know my exact energy footprint pattern and can control it. I know what is waste vs. necessity. I have completely eliminated expensive and unnecessary consumption." </br><em>-Chris Hunt, San Carlos CA</em></p>
             
            </div>
            
            
        </div> <!-- end of content -->
		
		
    	<div class="cleaner"></div>
    </div> <!-- end of main -->
    <div id="templatemo_footer">
    
        Copyright &#169; 2014 <a href="/">Mirax Development - Power Consumption Monitoring Software Application</a>
        
    </div> <!-- end of templatemo_footer -->
</div> <!-- end of wrapper -->
</div>
<g:javascript src = "logging.js" />

</body>
</html>